export type Item = [string, string, number | string | null, number | null];
export type Section = { cat: string; icon: string; items: Item[] };

export const MENU: Section[] = [
  { cat: "Appetizers", icon: "🍟", items: [
    ["Nachos Cheese Chicken", "ناتشوز دجاج بالجبنة", 125, 500],
    ["Fries Loaded Chicken", "بطاطس مقلية محشوة بالدجاج", 88, 350],
    ["Chicken Popcorn Chipotle", "دجاج بوب كورن شيبوتلي", 112, 450],
    ["Quesadillas Chicken", "كيساديالس دجاج", 100, 400],
    ["Chicken 65", "", 22, null],
    ["Chilli Chicken", "", 22, null],
    ["Chicken Majestic", "", 22, 350],
    ["Chapli Kabab", "", null, null],
  ]},
  { cat: "Barbeque", icon: "🔥", items: [
    ["Chicken Tikka Leg", "ساق دجاج تكا", 100, 400],
    ["Chicken Tikka Breast", "صدر دجاج تكا", 88, 350],
    ["Chicken Tawa Malai Breast", "صدر دجاج ماالي تاوا", 88, 350],
    ["Chicken Tawa Malai Leg", "ساق دجاج ماالي تاوا", 100, 400],
    ["Green Chicken Tikka Leg", "ساق دجاج تكا أخضر", 100, 400],
    ["Green Chicken Tikka Breast", "صدر دجاج تكا أخضر", 15, 350],
    ["Chicken Boti Boneless Tikka", "قطع دجاج تكا بدون عظم", 112, 450],
    ["Chicken Boti Boneless Malai", "قطع دجاج ماالي بدون عظم", 112, 450],
    ["Chicken Boti Bihari", "قطع دجاج بيهاري", 112, 450],
    ["Chicken Reshmi Kebab", "كباب دجاج ريشمي", 34, 450],
    ["Beef Boti Bihari", "قطع لحم بقر بيهاري", 125, 500],
    ["Beef Seekh Kebab", "كباب سيخ لحم بقر", 100, 400],
    ["Green Boti with Bone", "قطع خضراء بالعظم", 100, 400],
    ["Boti Afghani", "بوتي الأفغاني", 170, 620],
    ["Boti Namken", "بوتي نامكين", 112, 450],
    ["Boti Shangrila", "بوتي شانغريال", 34, 450],
    ["Mixed BBQ Platter", "طبق مشاوي مشكل", 90, 950],
    ["Malai Boti Platter", "", 34, null],
    ["Chicken Boti Kabab", "", 34, null],
  ]},
  { cat: "Shinwari Karahi", icon: "🍲", items: [
    ["Chicken Karahi Shinwari (Half/Full)", "شنواري دجاج كراهي", "45/75", 450],
    ["Chicken Karahi Koyla (Half/Full)", "دجاج كوال كراهي", "112/175", 450],
    ["Mutton Karahi Shinwari (Half/Full)", "شنواري لحم ضأن كراهي", "70/120", 400],
    ["Mutton Karahi Koyla (Half/Full)", "لحم ضأن كوال كراهي", "100/165", 400],
  ]},
  { cat: "Nihari", icon: "🥘", items: [
    ["Nihari Sada (Single/Double)", "نهاري سادة", "100/165", 400],
  ]},
  { cat: "Curries", icon: "🍛", items: [
    ["Chicken Makhni Handi", "قدر دجاج ماخني", 112, 450],
    ["Butter Chicken Handi", "قدر دجاج بالزبدة", 112, 450],
    ["Beef Special Kabab Fry", "كباب لحم بقر مقلي", 125, 500],
    ["Daal Makhni Handi", "قدر دال ماخني", 100, 400],
    ["Chicken Masala", "", 36, null],
    ["Mutton Masala", "", 33, null],
    ["Paneer Butter Masala", "", 34, null],
  ]},
  { cat: "Biryani & Rice", icon: "🍚", items: [
    ["Dum Biryani", "", 28, null],
    ["Hyderabadi Chicken Dum Biryani", "", 28, null],
    ["Chicken Tikka Biryani", "", 32, null],
  ]},
  { cat: "Rolls", icon: "🌯", items: [
    ["Chicken Tikka Chutney Roll", "رول دجاج تكا بالتشتني", 112, 450],
    ["Chicken Garlic Mayo Roll", "رول دجاج بمايونيز الثوم", 112, 450],
    ["Chicken Tikka BBQ Sauce Roll", "رول دجاج تكا بصوص الشواء", 112, 450],
    ["Chicken Spicy Juicy Roll", "رول دجاج حار وشهي", 112, 450],
    ["Chicken Bihari Roll", "رول دجاج بيهاري", 150, 600],
    ["Beef Bihari Roll", "رول لحم بقر بيهاري", 125, 500],
    ["Zinger Roll", "رول زينجر", 100, 400],
    ["Beef Seekh Kebab Roll", "رول كباب سيخ لحم بقر", 125, 500],
    ["Chicken Malai Boti Roll", "رول قطع دجاج ماالي", 112, 450],
    ["Chicken Reshmi Kebab Roll", "رول دجاج ريشمي", 112, 450],
    ["Chicken Chatkhara Roll", "رول دجاج تشاتخارا", 17, 460],
    ["Special Roll", "رول خاص", 115, 460],
  ]},
  { cat: "Burgers & Sandwiches", icon: "🍔", items: [
    ["Zinger Cheese Burger", "برجر زينجر بالجبنة", 175, 700],
    ["Chicken Juicy Lucy Cheese Burger", "برجر جوسي لوسي دجاج بالجبن", 20, 400],
    ["Original Club Sandwich", "ساندويتش كلوب أصلي", 100, 400],
    ["Chicken Tikka Club Sandwich", "ساندويتش كلوب تكا دجاج", null, 350],
    ["Half Chicken Broast + Bun & Fries", "نصف دجاجة مشوية مع خبز وبطاطس مقلية", 17, 600],
    ["Spicy Half Chicken Broast + Bun & Fries", "نصف دجاجة مشوية حارة مع خبز وبطاطس", 18, 600],
    ["Bun Kabab", "كعكة كباب", 12, 230],
    ["Grill Onion Burger", "برجر البصل المشوي", 15, 125],
    ["BBQ Reshmi Burger", "برجر ريشمي مشوي", 16, 400],
    ["BBQ Malai Burger", "برجر ماالي مشوي", 16, 400],
    ["BBQ Chicken Burger", "برجر دجاج مشوي", 16, 450],
    ["BBQ Bihari Burger", "برجر بيهاري مشوي", 16, 400],
    ["Chicken Burger", "برجر دجاج", 15, 400],
  ]},
  { cat: "Sandwiches (Grilled)", icon: "🥪", items: [
    ["Egg and Cheese Sandwich", "ساندويتش البيض والجبن", 12, 400],
    ["Grilled Chicken Sandwich", "ساندويتش دجاج مشوي", 16, 400],
    ["BBQ Chicken Sandwich", "ساندويتش دجاج باربكيو", 16, 400],
    ["BBQ Malai Sandwich", "ساندويتش ماالي باربكيو", 16, 400],
    ["BBQ Reshmi Sandwich", "ساندويتش ريشمي مشوي", 16, 400],
    ["BBQ Bihari Sandwich", "ساندويتش بيهاري مشوي", 16, 400],
    ["Chapli Sandwich", "", 16, null],
    ["Malai Boti Sandwich", "", 16, null],
  ]},
  { cat: "Breakfast", icon: "🍳", items: [
    ["Halwa Puri Platter", "صحن حلوة وبوري", 100, 400],
    ["3 Puri, Aloo, Channa, Halwa & Achar", "3 بوري، بطاطس، حمص، حلوة، مخلل", null, null],
    ["Desi Omelet + Lacha Paratha & Halwa", "أومليت بلدي مع براتا وحلوة", 13, 400],
    ["Sada Nihari + 2 Naan & Halwa", "نهاري سادة مع نان وحلوة", 20, 400],
    ["Anda Chana", "بيض شانا", 12, 400],
    ["Paya", "لحم ضأن باية", 20, 360],
    ["Sada Lacha Paratha", "براتا لاشا سادة", 4, 250],
    ["Omelette", "عجة", 3, 154],
    ["Half Fry", "بيضة نصف مقلية", 2, 110],
    ["Tea", "شاي", 3, null],
  ]},
  { cat: "Tandoori Bread", icon: "🫓", items: [
    ["Rumali Roti", "خبز رومالي", 1, 300],
    ["Plain Naan", "نان سادة", 100, 400],
    ["Butter Naan", "نان بالزبدة", 2, 400],
    ["Tandoori Roti", "خبز تنور", 88, 350],
    ["Lacha Paratha", "براتا لاشا", 4, 400],
    ["Puri Paratha", "براتا بوري", 112, 450],
  ]},
  { cat: "Drinks", icon: "🥤", items: [
    ["Water", "ماء", 1, 0],
    ["Soft Drinks", "مشروبات غازية", 3.5, 200],
    ["Limca Red Chilies", "مشروب ليمكا بالفلفل الأحمر", 11, 44],
    ["Lemon Fresh", "ليمون طازج", 10, 55],
    ["Lassi Plain", "لاسي سادة", 45, 180],
    ["Lassi Salty", "لاسي مالح", 38, 150],
    ["Lassi Mango", "لاسي مانجو", 35, 150],
    ["Falooda Special", "فالودة خاص", 15, 440],
    ["Falooda Kulfi", "فالودة كلفي", 15, 530],
    ["Lemonade Mint", "عصير الليمون بالنعناع", 10, 75],
    ["Shake Kit Kat", "هزة كيت كات", 16, 350],
    ["Shake Oreo", "هزة أوريو", 16, 350],
    ["Shake Snickers", "هزة سنيكرز", 16, 350],
    ["Shake Vanilla", "هزة الفانيليا", 16, 400],
    ["Orange Juice", "", 10, null],
    ["Pakola", "", 5, null],
  ]},
  { cat: "Tacos", icon: "🌮", items: [
    ["Chicken Fajita Tacos (2pc)", "تاكو دجاج فاهيتا قطعتين", 112, 450],
    ["Chicken Tikka Tacos (2pc)", "تاكو دجاج تكا قطعتين", 112, 450],
    ["Chicken Crispy Tacos (2pc)", "تاكو دجاج مقرمش قطعتين", 112, 450],
  ]},
  { cat: "Mexican", icon: "🌯", items: [
    ["Chicken Tikka Burrito Bowl", "صحن بوريتو دجاج تكا", 112, 450],
    ["Chicken Fajita Burrito Bowl", "صحن بوريتو دجاج فاهيتا", 112, 450],
    ["Chicken Crispy Burrito Bowl", "صحن بوريتو دجاج مقرمش", 112, 450],
  ]},
  { cat: "Pizzas", icon: "🍕", items: [
    ["Tikka Chicken (Small/Medium/Large)", "بيتزا دجاج تكا", "88/300/425", 1200],
    ["Fajita Chicken (Small/Medium/Large)", "بيتزا دجاج فاهيتا", "88/325/450", 1300],
    ["Malai Chicken (Small/Medium/Large)", "بيتزا دجاج ماالي", "88/300/425", 1200],
    ["Vegetarian (Small/Medium/Large)", "بيتزا خضروات (نباتية)", "20/25/38", 1000],
    ["Cheesy (Small/Medium/Large)", "بيتزا جبنة", "20/25/38", 1000],
    ["Kebab Bihari Chicken (Small/Medium/Large)", "بيتزا كباب دجاج بيهاري", "22/30/43", 1200],
    ["Kebab Reshmi Chicken (Small/Medium/Large)", "بيتزا كباب دجاج ريشمي", "88/112/175", 450],
    ["Kebab Seekh Beef (Small/Medium/Large)", "بيتزا كباب سيخ لحم بقر", "22/30/43", 400],
    ["Boti Bihari Beef (Small/Medium/Large)", "بيتزا لحم بقر بيهاري", "22/30/43", 1200],
    ["Cheese Crust Pizza (Med/Large)", "بيتزا قشرة الجبن", "38/50", 1000],
    ["Kabab Crust Pizza (Med/Large)", "بيتزا بعجينة الكباب", "45/60", 400],
    ["Crown Crust Pizza (Med/Large)", "بيتزا قشرة التاج", "45/60", 1000],
    ["Fries Pizza", "بيتزا بطاطا", 22, null],
  ]},
  { cat: "Fries", icon: "🍟", items: [
    ["Fries Spicy", "بطاطس مقلية حارة", 88, 350],
    ["Fries Plain", "بطاطس مقلية عادية", 88, 350],
    ["Fries Mayonnaise Garlic Spicy", "بطاطس حارة بالمايونيز والثوم", 10, 550],
    ["Fries BBQ Spicy", "بطاطس حارة بنكهة الباربكيو", 90, 400],
    ["Fries Mayonnaise Garlic Plain", "بطاطس عادية بالمايونيز والثوم", 88, 350],
    ["Fries BBQ Plain", "بطاطس عادية بنكهة الباربكيو", 88, 350],
  ]},
  { cat: "Thali", icon: "🍱", items: [
    ["Mixed BBQ Thali", "ثالي مشكل مع مشاوي", 305, 1410],
    ["Chicken Boti Malai Thali", "ثالي مشكل مع مشاوي (ماالي)", 305, 1410],
    ["Leg Tikka Thali", "ثالي مشكل مع تكا ليج", 305, 1410],
  ]},
];